# Generated by Django 3.2.7 on 2021-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_uploadfolder_synth_index_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='synth_index_array',
            field=models.JSONField(),
        ),
    ]
